import { View, Text, Dimensions, StyleSheet, PanResponder, Platform, Animated, } from 'react-native'
import React, { useEffect, useRef, useState } from 'react'
import { ScrollView, TouchableWithoutFeedback } from 'react-native-gesture-handler';
import Ionicons from "react-native-vector-icons/Ionicons";
import { HandleArrayDayCorrespondingPeriods2 } from './HandleArrayDay2';

interface DataPNLType {
  dayNumber: number,
  valuePNL: number
}
interface DataPNLFromServer{
year: number,
dataPNL: DataPNLType[][]
}
interface CalenderPnlAllYear {
  year: number,
  monthDetails: CalenderMonthDetails[]
}
interface CalenderMonthDetails{
  monthInNumber: number,
  monthName: string,
  dataPNL?: DataPNLType[][],
}

interface CalenderEachYearInfo{
  year: number,
  monthNames: string[],
  monthNumbers: number[]
}
interface MyCalenderChartProps{
  timePeriods: number
}
const {width, height} = Dimensions.get('screen');

export default function MyCalenderChart2({timePeriods = 6}: MyCalenderChartProps) {

    // Size calender
    const calenderWidth = width - 30; // 30 is total value of padding horizontal of the screen.
    const calenderPadding = 10;
    const calenderCanSee = calenderWidth - 10 * 2;
    // Name of the day in week.
    const dayNameInWeek = ["Sun","Mon", "Tue", "Web", "Thu", "Fri", "Sat",];
    const monthNameInYear = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    const {currentDay, currentMonth, currentYear, currentDayName} = GetDate();

    const [activeDay, setActiveDay] = useState<number | null>(null);

    const [arrayYearNumber, setArrayYearNumber] = useState<number[]>([])
    const [listMonthName, setListMonthName] = useState<string[]>([]);
    const [arrayPNLEachMonth, setArrayPNLEachMonth] = useState<DataPNLType[][][]>([]);  // Array is arrange look like [3,2,1,12,11,10]. go back time.
    
    useEffect(() => {
      const getCalenderPnlData = HandleArrayDayCorrespondingPeriods2({arrayDataPNL: dataPNLForDayForSixMonths2, periods: timePeriods})
      if(getCalenderPnlData.length> 0){
        CreateArraySomeArrayFromDataPNL2(getCalenderPnlData); 
      }
      console.log('useEffect re-render');
      function CreateArraySomeArrayFromDataPNL2 (getCalenderPnlData: CalenderPnlAllYear[]){

        // Task 1: Create monthName array;
        let arrayMonthName: string[] = [];

        // Task 2: Create object that has info about limit of period such as "endMonth", "endYear".
        let objectEndMonthAndYear:{monthIndex: number, year: number, monthName: string} = {monthIndex: 1,monthName: "January", year: currentYear};

        // Task 3: Create array PNL. Follow this structure. [lastmonth,...,firstmonth].
        let arrayPnlAllYear: DataPNLType[][][] = []

        // Task 4: Create an array year. [2024,2024,2023,2023,2023]
        let arrayYearNumber: number[] = [];

        getCalenderPnlData.map((objYear: CalenderPnlAllYear, i: number) =>{
          const year = objYear.year;
          const monthDetails = objYear.monthDetails;
          // Solve task 1.
          let arrayMonthNameThisYear: string[] = [];
          let arrayPNLMonthThisYear: DataPNLType[][][] = [];
          
          monthDetails.map((monthDetail: CalenderMonthDetails, k : number) => {
            const monthName = monthDetail.monthName;
            const monthInNumber = monthDetail.monthInNumber;
            const dataPNL = monthDetail.dataPNL || [];
            arrayMonthNameThisYear.push(monthName);
            arrayPNLMonthThisYear.push(dataPNL);
            arrayYearNumber.push(year);
          })
          const reverseArrayMonthName = arrayMonthNameThisYear.reverse();
          arrayMonthName.push(...reverseArrayMonthName);

          const reverseArrayPnlAllYear = arrayPNLMonthThisYear.reverse();
          arrayPnlAllYear.push(...reverseArrayPnlAllYear)

          // Solve task 2.
          // Determine the last month and las year in calender
          if(i === getCalenderPnlData.length - 1){
            objectEndMonthAndYear.year = year;
            const lastMonthInCalender = objYear.monthDetails[0];
            objectEndMonthAndYear.monthIndex = lastMonthInCalender.monthInNumber;
            objectEndMonthAndYear.monthName = lastMonthInCalender.monthName;
          }

          // Solve task 3.
        });
        // console.log('arrayMonthName',arrayMonthName);

        // This result for task 1.
        setListMonthName(arrayMonthName);

        // This result for task 2.
        // setEndMonthYear(objectEndMonthAndYear);

        // This result for task 3.
        setArrayPNLEachMonth(arrayPnlAllYear);

        // This result for task 4.
        // console.log('arrayYearNumber',arrayYearNumber);
        setArrayYearNumber(arrayYearNumber.reverse());
        setA(arrayMonthName.length - 1)
      };
    },[timePeriods])

    const handleScroll = (event: any) => {
      setActiveDay(null);
      console.log('re-render at handleScroll');
      const { contentOffset, layoutMeasurement } = event.nativeEvent;
      const pageIndex = Math.ceil((contentOffset.x )/ width); 
        let newPageIndex = pageIndex;
        if(pageIndex === 0){
          newPageIndex = pageIndex + 1
        }
        console.log('pageIndex', pageIndex);
        if(pageIndex === listMonthName.length){
          return;
        }
        setA(pageIndex)
    };
  
    // const [isRun, setIsRun] = useState(false)
    // useEffect(() =>{
    //   setIsRun(true);
    // },[]);
    const scrollViewRef = useRef<ScrollView | null>(null);
    const [a, setA] = useState( 4 )
    const handleNextPage = () => {
      setActiveDay(null)
      console.log('next a',a);
      if(a === arrayPNLEachMonth.length - 1 ){
        return
      } else {
        if (scrollViewRef.current) {
          scrollViewRef.current.scrollTo({ x: (a+1)*(width -30), animated: true });
        }
        setA(a + 1)
      }
    }
    const handlePreviousPage = () => {
      setActiveDay(null);
      console.log('back a',a);
      if(a === 0){
        return
      } else {
        if (scrollViewRef.current) {

          scrollViewRef.current.scrollTo({ x: (a-1)*(width -30), animated: true });
        }
        setA(a - 1)
      }
    };

    console.log('re-render');

  return (
    <View style={{width:width, paddingHorizontal: 0, borderWidth: 0, borderColor:'gray'}}>
      {/* The heading of the callender that include "monthName, year, and two buttons for navigate between month" */}
      <View style={{display:'flex', flexDirection:'row', alignItems:'center', justifyContent:'space-between', width: calenderWidth, marginVertical: 10,position:'absolute',top: 0, zIndex:2,borderWidth: 0, borderColor:'red', paddingHorizontal:5}}>
        <View>
          <TouchableWithoutFeedback onPress={handlePreviousPage}>
            <View style={{width: 40, height:30, justifyContent:'center', alignItems:'center'}}>
              <Ionicons 
                name="chevron-back" 
                size={20} 
                color={a === 0 ? "gray" : "blue"} 
                style={{}} 
              />
            </View>
          </TouchableWithoutFeedback>
        </View>
        <View>
          <TouchableWithoutFeedback onPress={handleNextPage}>
            <View style={{width: 40, height:30, justifyContent:'center', alignItems:'center'}}>
              <Ionicons 
                name="chevron-back" 
                size={20} 
                color={a === arrayPNLEachMonth.length -1 ? 'gray' : "blue"} 
                style={{transform:[{rotate: '180deg'}]}} 
              />
            </View>
          </TouchableWithoutFeedback>
        </View>
      </View>
      {arrayPNLEachMonth.length > 0 && <ScrollView
        ref={scrollViewRef}
        contentContainerStyle={[{ width: Platform.OS === "ios" ? ((width -30)* arrayPNLEachMonth.length): width * arrayPNLEachMonth.length,},]}
        horizontal
        pagingEnabled
        showsHorizontalScrollIndicator={true}
        scrollEnabled={true}
        onScroll={handleScroll}
        scrollEventThrottle={16}
        contentOffset={{ x: (arrayPNLEachMonth.length - 1)*(width - 30), y: 0 }} // Set initial position to 4 times screen width 
        style={{width: calenderWidth}}
        
      >
        <View style={{width:"100%",borderBottomWidth:1, borderColor:'gray', flexDirection:'row',}}>
            { arrayPNLEachMonth.length > 0 && arrayPNLEachMonth.map((arrayPNL: DataPNLType[][], m: number) => {
              return (
                <View key={m} style={{ width: calenderWidth, display:'flex', flexDirection:'row', flexWrap:'wrap', justifyContent:'center', alignItems:'center',  }}>

                  {/* monthName and year */}
                  <View style={{ marginVertical: 10}}>
                    <Text style={{fontSize: 18, fontWeight: "500"}}>
                      {listMonthName?.[listMonthName.length - 1 - m]} {arrayYearNumber[m]}
                    </Text>
                  </View>
                  
                  {/* This is create the shoter dayName (Sun, Mon, Tue ...) */}
                  <View style={{display:'flex', flexDirection:'row', alignItems:'center', width: calenderWidth, marginVertical: 10, paddingHorizontal: 0, justifyContent:'center',}}> 
                      {dayNameInWeek.map((dayName: string, i: number) => {
                          return(
                              <Text key={i} style={{width: calenderCanSee / 7, textAlign: 'center'}}>
                                  {dayName}
                              </Text>
                          )
                      })}
                  </View>
                  {arrayPNL.map((pnlForThisMonth: DataPNLType[], i: number) =>{
                      return(
                        // this code draw the line in calender
                          <View key={i} style={{ width: calenderWidth, height: calenderCanSee/7, display:'flex', flexDirection:'row', marginBottom: 5,paddingHorizontal: 0, justifyContent:'center'}}>
                              {pnlForThisMonth.length > 0 && pnlForThisMonth.map((dayData: DataPNLType, i: number) => {
                                  const dayNumber = dayData.dayNumber ;
                                  const dayPNL = dayData.valuePNL ;
                                  return (
                                      <TouchableWithoutFeedback onPress={() => {console.log('touch in day'); setActiveDay(dayNumber === activeDay ? null : (dayNumber === 0 ? null : dayNumber))}} key={i}>
                                        <View style={[styles.decorLineShowDate, {width: calenderCanSee / 7,height: calenderCanSee/7, backgroundColor: dayNumber === activeDay ? "pink" : "white",}]}>
                                          <Text style={{ textAlign:'center', fontSize:13, fontWeight:"600", }}>
                                              {dayNumber !== 0 ? dayNumber : ""}
                                          </Text>
                                          <Text style={{color: dayPNL > 0 ? "green" : "red", fontSize: 12}}>
                                              {dayPNL > 0 ? "+" : (dayPNL !== 0 ? "-" : "")}
                                              {dayPNL !== 0 ? dayPNL : ""}
                                          </Text>
                                        </View>
                                      </TouchableWithoutFeedback>
                                  )
                              })}
                          </View>
                      )
                  })}
                </View>
            )})}
          </View>
      </ScrollView>}
    </View>
  )
}
// Stylesheet
const styles = StyleSheet.create({
  decorLineShowDate: {
    display:'flex', 
    justifyContent:'center', 
    alignItems:'center', 
    padding: 5,
    borderWidth: 0, 
    borderColor:'gray', 
    borderRadius: 5,
  },
})

function GetDate(){
    const currentDate = new Date();

    const currentDay = currentDate.getDate();
    const currentMonth = currentDate.getMonth() + 1; // Months are zero-indexed, so we add 1
    const currentYear = currentDate.getFullYear();

    // Get the name of the current day
    const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", ];
    const currentDayName = dayNames[currentDate.getDay()];

    return {
        "currentDay": currentDay,
        "currentMonth": currentMonth,
        "currentYear": currentYear,
        "currentDayName": currentDayName
    }
}
const dataPNL2 = [
    [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      }, {
        dayNumber: 30,
        valuePNL: 100
      }, {
        dayNumber: 31,
        valuePNL: 100
      }],
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 0
      }, {
        dayNumber: 23,
        valuePNL: 0
      }, {
        dayNumber: 24,
        valuePNL: 0
      }, {
        dayNumber: 25,
        valuePNL: 0
      }, {
        dayNumber: 26,
        valuePNL: 0
      }, {
        dayNumber: 27,
        valuePNL: 0
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      }, {
        dayNumber: 30,
        valuePNL: 100
      }, {
        dayNumber: 31,
        valuePNL: 100
      }]
]

const dataPNL: DataPNLType[] = [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }]
  const dataPNLForDayInMonth: DataPNLType[] = [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }]
const dataPNLForDayInYear: DataPNLType[][] = [
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }]
]
const dataPNLForDayInYear2: DataPNLType[][] = [
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }]
]

const dataPNLForDayInPreviousYear: DataPNLType[][] = [
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, ],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, ],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
]
const dataPNLForDayForOneYear: DataPNLType[][] = [
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, ],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, ],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
]
const dataPNLForDayForSixMonths: DataPNLType[][] = [
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  },
  {
    dayNumber: 29,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  }, {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },
  {
    dayNumber: 31,
    valuePNL: 100
  }],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  }, {
    dayNumber: 30,
    valuePNL: 100
  },],
  [{
    dayNumber: 1,
    valuePNL: 100
  }, {
    dayNumber: 2,
    valuePNL: 100
  }, {
    dayNumber: 3,
    valuePNL: 100
  }, {
    dayNumber: 4,
    valuePNL: 100
  }, {
    dayNumber: 5,
    valuePNL: 100
  }, {
    dayNumber: 6,
    valuePNL: 100
  }, {
    dayNumber: 7,
    valuePNL: 100
  }, {
    dayNumber: 8,
    valuePNL: 100
  }, {
    dayNumber: 9,
    valuePNL: 100
  }, {
    dayNumber: 10,
    valuePNL: 100
  }, {
    dayNumber: 11,
    valuePNL: 100
  }, {
    dayNumber: 12,
    valuePNL: 100
  }, {
    dayNumber: 13,
    valuePNL: 100
  }, {
    dayNumber: 14,
    valuePNL: 100
  }, {
    dayNumber: 15,
    valuePNL: 100
  }, {
    dayNumber: 16,
    valuePNL: 100
  }, {
    dayNumber: 17,
    valuePNL: 100
  }, {
    dayNumber: 18,
    valuePNL: 100
  }, {
    dayNumber: 19,
    valuePNL: 100
  }, {
    dayNumber: 20,
    valuePNL: 100
  }, {
    dayNumber: 21,
    valuePNL: 100
  }, {
    dayNumber: 22,
    valuePNL: 100
  }, {
    dayNumber: 23,
    valuePNL: 100
  }, {
    dayNumber: 24,
    valuePNL: 100
  }, {
    dayNumber: 25,
    valuePNL: 100
  }, {
    dayNumber: 26,
    valuePNL: 100
  }, {
    dayNumber: 27,
    valuePNL: 100
  }, {
    dayNumber: 28,
    valuePNL: 100
  }, {
    dayNumber: 29,
    valuePNL: 100
  },  {
    dayNumber: 30,
    valuePNL: 100
  },{
    dayNumber: 31,
    valuePNL: 100
  },],
]

const dataPNLForDayForSixMonths2: DataPNLFromServer[] = [
  {
    year: 2024,
    dataPNL: [
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      }, {
        dayNumber: 30,
        valuePNL: 100
      }, {
        dayNumber: 31,
        valuePNL: 100
      }],
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      },
      {
        dayNumber: 29,
        valuePNL: 100
      }],
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      }, {
        dayNumber: 30,
        valuePNL: 100
      }, {
        dayNumber: 31,
        valuePNL: 100
      }],
    ]
  },
  {
    year: 2023,
    dataPNL: [
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      }, {
        dayNumber: 30,
        valuePNL: 100
      },
      {
        dayNumber: 31,
        valuePNL: 100
      }],
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      }, {
        dayNumber: 30,
        valuePNL: 100
      },],
      [{
        dayNumber: 1,
        valuePNL: 100
      }, {
        dayNumber: 2,
        valuePNL: 100
      }, {
        dayNumber: 3,
        valuePNL: 100
      }, {
        dayNumber: 4,
        valuePNL: 100
      }, {
        dayNumber: 5,
        valuePNL: 100
      }, {
        dayNumber: 6,
        valuePNL: 100
      }, {
        dayNumber: 7,
        valuePNL: 100
      }, {
        dayNumber: 8,
        valuePNL: 100
      }, {
        dayNumber: 9,
        valuePNL: 100
      }, {
        dayNumber: 10,
        valuePNL: 100
      }, {
        dayNumber: 11,
        valuePNL: 100
      }, {
        dayNumber: 12,
        valuePNL: 100
      }, {
        dayNumber: 13,
        valuePNL: 100
      }, {
        dayNumber: 14,
        valuePNL: 100
      }, {
        dayNumber: 15,
        valuePNL: 100
      }, {
        dayNumber: 16,
        valuePNL: 100
      }, {
        dayNumber: 17,
        valuePNL: 100
      }, {
        dayNumber: 18,
        valuePNL: 100
      }, {
        dayNumber: 19,
        valuePNL: 100
      }, {
        dayNumber: 20,
        valuePNL: 100
      }, {
        dayNumber: 21,
        valuePNL: 100
      }, {
        dayNumber: 22,
        valuePNL: 100
      }, {
        dayNumber: 23,
        valuePNL: 100
      }, {
        dayNumber: 24,
        valuePNL: 100
      }, {
        dayNumber: 25,
        valuePNL: 100
      }, {
        dayNumber: 26,
        valuePNL: 100
      }, {
        dayNumber: 27,
        valuePNL: 100
      }, {
        dayNumber: 28,
        valuePNL: 100
      }, {
        dayNumber: 29,
        valuePNL: 100
      },  {
        dayNumber: 30,
        valuePNL: 100
      },{
        dayNumber: 31,
        valuePNL: 100
      },],
    ]
  }
]